# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ner_model.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fner_model.proto\x12\x0bner_backend\"\x1d\n\nNERRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0bNERResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x96\x01\n\x13TranscriptionResult\x12\x12\n\ntranscript\x18\x01 \x01(\t\x12\x12\n\nstart_time\x18\x02 \x01(\x02\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\x02\x12\x15\n\rspeaking_rate\x18\x04 \x01(\x02\x12.\n\x0fword_timestamps\x18\x05 \x03(\x0b\x32\x15.ner_backend.WordInfo\"R\n\x08WordInfo\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x12\n\nstart_time\x18\x02 \x01(\x02\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\x02\x12\x12\n\nconfidence\x18\x04 \x01(\x02\"\x85\x01\n\x1bStreamingTranscribeResponse\x12\x31\n\x07results\x18\x01 \x03(\x0b\x32 .ner_backend.TranscriptionResult\x12\x10\n\x08is_final\x18\x02 \x01(\x08\x12\x0f\n\x07version\x18\x04 \x01(\t\x12\x10\n\x08\x64uration\x18\x07 \x01(\x02\x32\x64\n\nNERBackend\x12V\n\x0cStreamingNER\x12(.ner_backend.StreamingTranscribeResponse\x1a\x18.ner_backend.NERResponse(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ner_model_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NERREQUEST._serialized_start=32
  _NERREQUEST._serialized_end=61
  _NERRESPONSE._serialized_start=63
  _NERRESPONSE._serialized_end=93
  _TRANSCRIPTIONRESULT._serialized_start=96
  _TRANSCRIPTIONRESULT._serialized_end=246
  _WORDINFO._serialized_start=248
  _WORDINFO._serialized_end=330
  _STREAMINGTRANSCRIBERESPONSE._serialized_start=333
  _STREAMINGTRANSCRIBERESPONSE._serialized_end=466
  _NERBACKEND._serialized_start=468
  _NERBACKEND._serialized_end=568
# @@protoc_insertion_point(module_scope)
