// user fields
const PASSWORD_MIN_LENGTH = 8;
const PASSWORD_MAX_LENGTH = 12;
const NAME_MAX_LENGTH = 45;
const SURNAME_MAX_LENGTH = 45;
const DENTISTID_MAX_LENGTH = 45;

const EX_DATA = [
  {
    quadrant: 1,
    side: "buccal",
    idxArray: [
      {
        ID: 1,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 2,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 3,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 4,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 5,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 6,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 7,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 8,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
    ],
  },
  {
    quadrant: 1,
    side: "lingual",
    idxArray: [
      {
        ID: 1,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 2,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 3,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 4,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 5,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 6,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 7,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 8,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
    ],
  },
  {
    quadrant: 2,
    side: "buccal",
    idxArray: [
      {
        ID: 1,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 2,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 3,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 4,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 5,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 6,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 7,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 8,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
    ],
  },
  {
    quadrant: 2,
    side: "lingual",
    idxArray: [
      {
        ID: 1,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 2,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 3,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 4,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 5,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 6,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 7,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 8,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
    ],
  },
  {
    quadrant: 3,
    side: "buccal",
    idxArray: [
      {
        ID: 1,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 2,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 3,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 4,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 5,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 6,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 7,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 8,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
    ],
  },
  {
    quadrant: 3,
    side: "lingual",
    idxArray: [
      {
        ID: 1,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 2,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 3,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 4,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 5,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 6,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 7,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 8,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
    ],
  },
  {
    quadrant: 4,
    side: "buccal",
    idxArray: [
      {
        ID: 1,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 2,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 3,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 4,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 5,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 6,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 7,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 8,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
    ],
  },
  {
    quadrant: 4,
    side: "lingual",
    idxArray: [
      {
        ID: 1,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 2,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 3,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 4,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 5,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 6,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 7,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
      {
        ID: 8,
        PD: [0, 0, 0],
        RE: [0, 0, 0],
        BOP: [0, 0, 0],
        MO: 0,
        MGJ: 0,
      },
    ],
  },
];

export {
  PASSWORD_MIN_LENGTH,
  PASSWORD_MAX_LENGTH,
  NAME_MAX_LENGTH,
  SURNAME_MAX_LENGTH,
  DENTISTID_MAX_LENGTH,
  EX_DATA,
};
